### ISSUE TITLE
react-leaflet

### ISSUE THREAD

**Issue by pcpatfire** [Leaflet/Leaflet.TileLayer.NoGap#10]
Hi, is it possible to use the plugin with react-leaflet? If yes, how?
Thank you

**Comment by IvanSanchez** [comment]
TL;DR: I don't care about React, so it's your problem.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by pcpatfire** [comment]
Ok. I understand.
Please, can you tell me how can I use the plugin in vanilla Leaflet? 
For instance, how should I re-write the following code:
```
var Esri_WorldImagery = L.tileLayer(
'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', 
{
	attribution: 'Tiles &copy; Esri &mdash; etc.'
});
```
I already installed the plugin using npm.
Thank you

**Comment by IvanSanchez** [comment]
Study https://github.com/Leaflet/Leaflet.TileLayer.NoGap/blob/master/public-demo.html .

**Comment by pcpatfire** [comment]
Thank you for your answer. I don't know if this is a silly question, but why this modified TileLayer isn't included in the Leaflet pachake?

**Comment by IvanSanchez** [comment]
> why this modified TileLayer isn't included in the Leaflet package?

Lack of testing and maintainer time.
