### ISSUE TITLE
Worrking with GoogleMutant?

### ISSUE THREAD

**Issue by rs1-es** [Leaflet/Leaflet.TileLayer.NoGap#11]
Is there any way it can work with [https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant](https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant)?

**Comment by IvanSanchez** [comment]
No, since GoogleMutant is a GridLayer instead of a TileLayer due to how the hybrid (aerial+labels) tiles overlap each other.
